// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmnyxkeeumxtxjxbxzfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtbnl4a2VldW14dHhqeGJ4emZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQ5NjcsImV4cCI6MjA2Mzc3MDk2N30.4Q-rJ8hriPS_3Aeg6p-GW6mX0zbUYODciTXUc5HYyI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);